'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useState } from "react";
import Navbar from "./Navbar/Navbar";
import Navmob from "./Navbar/Nav2/Nav2";


import Footer from "./footerSection/footer";
// import { SetStateAction, useState } from "react";





const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  
  



  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const [isMenu, setIsMenu] = useState(false);
  console.log('hello ', isMenu )

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="w-full mini:h-[80px] xxs:h-[80px]">
  <Navbar/>
  </div> */}
 
    
   {/* NavMobversion */}
 <div className={` ${isMenu == true ? 'block' : 'hidden'} w-full h-full absolute -bg-blue-500 z-10 lg:hidden   `}>
        <Navmob setIsMenu={setIsMenu}/>
        
      </div>
{/* Navmob-Cloze */}


    {/* NVABAR */}
    <div className="w-full h-20 -bg-slate-500 bg-white flex items-center justify-center lg:px-10 xxs:px-0 ">
    <Navbar setIsMenu={setIsMenu}/>
    </div>


        {children}
        
{/* Footer Section */}
<div className="w-full h-auto -py-10 -bg-slate-400">
<Footer/>
</div>
      </body>
    </html>
  );
}
